server:
  port: ${PORT:8090}

spring:
  application:
    name: admin-server
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local


---

spring:
  config:
    activate:
      on-profile: prod